name: 从ROM提取boot

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: ''

jobs:
  magisk_unpack_and_patch:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip aria2 p7zip-full
          pip3 install backports.lzma protobuf pycrypto

      - name: 提取镜像
        run: |
          cd $HOME
          git clone --recurse-submodules https://github.com/tosasitill/Firmware_extractor.git
          cd Firmware_extractor
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          ./extractor.sh firmware.zip
  
      - name: 提交信息
        run: |
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M')" >> ${{ github.workspace }}/info.md
          echo "提交链接：https://gh.sb250.gq/" >> ${{ github.workspace }}/info.md
          echo "下载直链：${{ github.event.inputs.boot_url }}" >> ${{ github.workspace }}/info.md

      - name: 上传镜像
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "~/Firmware_extractor/out/*"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "Magisk_${{ env.BUILD_TIME }}_${{ github.run_id }}"
            token: ${{ secrets.GITHUB_TOKEN }}
            name: "${{ github.event.inputs.rom_url }}"
